In [ ]:
import torch

## Creating Layers

In [ ]:
class DenseLayer:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

## Activation Functions

### ReLU

In [ ]:
class Activation_ReLU:
  # Forward pass
  def forward(self, inputs):
    self.output = torch.max(torch.tensor(0),inputs)

### Sigmoid

In [ ]:
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1 / (1 + torch.exp(inputs*-1))

### Softmax

## Loss

In [ ]:
class Loss_MeanSquareError():
    # Forward pass
    def forward(self, y_pred, y_true):
        # Calculate the mean square error
        mse_loss = torch.mean((y_pred - y_true)**2)
        return mse_loss

## Accuracy

In [ ]:
class Accuracy():
  def calculate(self, y_pred, y_true):
    predictions = torch.argmax(y_pred, axis=1)
    if len(y_true.shape) == 2:
      y_true = torch.argmax(y_true, axis=1)
    accuracy = torch.mean((predictions == y_true).float())
    return accuracy

## Creating model

### BackPropagation

# $\frac{\partial Loss}{\partial w_n}$

#### Model

In [ ]:
X = torch.tensor([0.4, 0.9])
y = torch.tensor([0.15, 0.85])

In [ ]:
hidden_layer_1 = DenseLayer(2, 2)
activation1 = Activation_ReLU()
output_layer = DenseLayer(2, 2)
activation2 = Activation_Sigmoid()

In [ ]:
hidden_layer_1.forward(X)
activation1.forward(hidden_layer_1.output)
output_layer.forward(activation1.output)
activation2.forward(output_layer.output)
activation2.output

tensor([[0.5000, 0.5000]])

In [11]:
def back_prop_two_neuron(fp):
  lr = torch.tensor(0.01)
  back1 = (fp[0][0]-y[0])*(1-fp[0][0])*fp[0][0]
  back2 = (fp[0][1]-y[1])*(1-fp[0][1])*fp[0][1]
  output_layer.weights[0][0] -= lr * back1*activation1.output[0][0]
  output_layer.weights[0][1] -= lr * back1*activation1.output[0][1]
  output_layer.weights[1][0] -= lr * back2*activation1.output[0][0]
  output_layer.weights[1][1] -= lr * back2*activation1.output[0][1]
  output_layer.biases[0][0] -= lr * back1
  output_layer.biases[0][1] -= lr * back2

  hidden_layer_1.weights[0][0] -= lr * (back1 * output_layer.weights[0][0] * X[0] + back2 * output_layer.weights[0][1] * X[0] ) if hidden_layer_1.output[0][0] > 0 else 0
  hidden_layer_1.weights[0][1] -= lr * (back1 * output_layer.weights[0][0] * X[1] + back2 * output_layer.weights[0][1] * X[1] ) if hidden_layer_1.output[0][0] > 0 else 0
  hidden_layer_1.weights[1][0] -= lr * (back1 * output_layer.weights[1][0] * X[0] + back2 * output_layer.weights[1][1] * X[0] ) if hidden_layer_1.output[0][1] > 0 else 0
  hidden_layer_1.weights[1][1] -= lr * (back1 * output_layer.weights[1][0] * X[1] + back2 * output_layer.weights[1][1] * X[1] ) if hidden_layer_1.output[0][1] > 0 else 0
  hidden_layer_1.biases[0][0] -= lr * (back1 * output_layer.weights[0][0] + back2 * output_layer.weights[0][1] ) if hidden_layer_1.output[0][0] > 0 else 0
  hidden_layer_1.biases[0][1] -= lr * (back1 * output_layer.weights[1][0] + back2 * output_layer.weights[1][1] ) if hidden_layer_1.output[0][1] > 0 else 0

In [13]:
print("Output after the backpropagation")
back_prop_two_neuron(activation2.output)
print("Hidden Layer 1 weight\n",hidden_layer_1.weights)
print("Hidden Layer 1 bias\n", hidden_layer_1.biases)
print("Output Layer weight\n", output_layer.weights)
print("Output Layer bias\n",output_layer.biases)


Output after the backpropagation
Hidden Layer 1 weight
 tensor([[0.0004, 0.0030],
        [0.0048, 0.0095]])
Hidden Layer 1 bias
 tensor([[-8.1157e-07,  6.8982e-06]])
Output Layer weight
 tensor([[0.0084, 0.0079],
        [0.0055, 0.0094]])
Output Layer bias
 tensor([[-0.0018,  0.0017]])
